import mongoose from 'mongoose';

const parentReportSchema = new mongoose.Schema(
  {
    parent: {
      type:     mongoose.Schema.Types.ObjectId,
      ref:      'User',
      required: true,
      index:    true,
    },
    child: {
      type:     mongoose.Schema.Types.ObjectId,
      ref:      'User',
      required: true,
      index:    true,
    },
    reportType: {
      type:    String,
      enum:    ['weekly', 'monthly', 'custom', 'on_demand'],
      default: 'weekly',
    },
    period: {
      startDate: { type: Date, required: true },
      endDate:   { type: Date, required: true },
    },
    // Snapshot of data at report generation time
    snapshot: {
      study: {
        totalMinutes:     { type: Number, default: 0 },
        totalSessions:    { type: Number, default: 0 },
        avgDailyMinutes:  { type: Number, default: 0 },
        avgFocusScore:    { type: Number, default: null },
        topSubjects:      [{ subject: String, minutes: Number }],
        longestStreak:    { type: Number, default: 0 },
        activeDays:       { type: Number, default: 0 },
      },
      tasks: {
        total:          { type: Number, default: 0 },
        completed:      { type: Number, default: 0 },
        overdue:        { type: Number, default: 0 },
        completionRate: { type: Number, default: 0 },
        xpEarned:       { type: Number, default: 0 },
      },
      assignments: {
        submitted:    { type: Number, default: 0 },
        avgGrade:     { type: Number, default: null },
        lateCount:    { type: Number, default: 0 },
        passCount:    { type: Number, default: 0 },
      },
      pomodoro: {
        totalSessions:  { type: Number, default: 0 },
        totalCycles:    { type: Number, default: 0 },
        totalWorkMins:  { type: Number, default: 0 },
      },
      highlights:  [{ type: String }],
      concerns:    [{ type: String }],
      dailyActivity: [
        {
          date:    String,
          minutes: Number,
          sessions:Number,
        },
      ],
    },
    generatedAt:  { type: Date, default: Date.now },
    isAutoGenerated:{ type: Boolean, default: false },
    isRead:       { type: Boolean, default: false },
    readAt:       { type: Date, default: null },
  },
  { timestamps: true }
);

parentReportSchema.index({ parent: 1, child: 1, generatedAt: -1 });

const ParentReport = mongoose.model('ParentReport', parentReportSchema);
export default ParentReport;